プレゼミ～第二回～
khirotaka/tigerfish pull request #12
Opened 2020-12-01 07:05 UTC by hiro-Anzai

３年生の第二回のコードを書きました。
内容は、タイタニックデータを決定木とKnnで精度比較することです。

2020-12-01 07:25 UTC, khirotaka requested changes
ディレクトリトップにある.ipynbを削除する

2020-12-01 07:26 UTC, khirotaka requested changes
2ブロック目、
```python
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
```
の `train.csv`と`test.csv` はどこからきた？

2020-12-01 07:32 UTC, khirotaka requested changes
## データセットの欠損確認
```python
train = train.drop(["PassengerId", "Name", "Ticket", "Cabin"],axis=1)
test = test.drop(["PassengerId","Name", "Ticket", "Cabin"],axis=1)
```

**コーディング規約違反**
```
 "Cabin"], axis=1)    # <- スペースを開ける
```

## 前処理（データセットの事前処理）
```python
#Embarkedをダミー変数化
train = pd.get_dummies(train,columns=["Embarked"])
test = pd.get_dummies(test,columns=["Embarked"])
``` 
上と同じ

```python
#訓練データとテストデータに分割
train_set, test_set = train_test_split(train, test_size = 0.2, random_state = 1) # キーワード引数の場合スペースを入れない

X_train = train_set.iloc[:,1:]     # スペースを入れる。X_train のように変数名に大文字はコーディング規約違反
y_train = train_set.iloc[:,0]     # スペースを入れる

X_test = test_set.iloc[:,1:]
y_test = test_set.iloc[:,0]
```

```python
#決定木モデルの作成
K = 5    # 大文字にしない
clf1 =DecisionTreeClassifier(max_depth=K)    # スペースを入れる
clf1 = clf1.fit(X_train, y_train)
```

2020-12-01 07:34 UTC, khirotaka reviewed
全体的にコーディング規約違反が多いです。ちゃんとColab上で実行しましたか？
先に書いたように、`train.csv` などはどこから来たんですか？

修正してください。

また、このプログラムは動きませんでしたか？

https://github.com/khirotaka/tigerfish/blob/master/utils/support.py

2020-12-01 07:36 UTC, khirotaka commented
あと、[作成手順](https://github.com/khirotaka/tigerfish/issues/1#issue-745784989)は読みましたか？
配布するスライドやドキュメントを `docs/自分が担当する回の名前/` に保存してください。

2020-12-01 07:59 UTC, hiro-Anzai commented
１つ目、
https://www.kaggle.com/c/titanic/data
このサイトから
train.csv
test.csv
ダウンロードしました。
それをcolaboratoryのcsvファイル読み込ませました。
２つ目、
コーディング規約違反については修正します。
3つ目、
プログラムについては実行していないのでこれから動かします。

2020-12-04 02:15 UTC, hiro-Anzai commented
作成手順のPowerPointをアップしました。
とコーディング規約違反についてコードを修正しました。

2020-12-04 02:22 UTC, khirotaka commented
コメントを読みましたか？
直接指導します。

2020-12-05 12:28 UTC, khirotaka approved these changes
#1 やその他で指定したディレクトリに保存されていないためこちらで修正しました。
今後は、ちゃんと日本語で書かれている文章を読むようにしてください。

2020-12-05 12:28 UTC, merged